<template><div><div class="language-sql line-numbers-mode" data-ext="sql" data-title="sql"><pre v-pre class="language-sql"><code><span class="line"><span class="token keyword">create</span> <span class="token keyword">table</span> 社团表<span class="token punctuation">(</span></span>
<span class="line">	社团号 <span class="token keyword">char</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span> <span class="token keyword">PRIMARY</span> <span class="token keyword">KEY</span><span class="token punctuation">,</span></span>
<span class="line">    名称 <span class="token keyword">char</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    活动地点 <span class="token keyword">char</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">create</span> <span class="token keyword">table</span> 学生表<span class="token punctuation">(</span></span>
<span class="line">	学号 <span class="token keyword">char</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span> <span class="token keyword">PRIMARY</span> <span class="token keyword">KEY</span><span class="token punctuation">,</span></span>
<span class="line">    姓名 <span class="token keyword">char</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    性别 <span class="token keyword">char</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    出生日期 <span class="token keyword">char</span><span class="token punctuation">(</span><span class="token number">32</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">create</span> <span class="token keyword">table</span> 参加社团表<span class="token punctuation">(</span></span>
<span class="line">    社团号 <span class="token keyword">char</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">	学号 <span class="token keyword">char</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">	加入时间 <span class="token keyword">char</span><span class="token punctuation">(</span><span class="token number">32</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">	<span class="token keyword">PRIMARY</span> <span class="token keyword">KEY</span><span class="token punctuation">(</span>社团号<span class="token punctuation">,</span>学号<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">	<span class="token keyword">FOREIGN</span> <span class="token keyword">KEY</span> <span class="token punctuation">(</span>学号<span class="token punctuation">)</span> <span class="token keyword">REFERENCES</span> 学生表<span class="token punctuation">(</span>学号<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">	<span class="token keyword">FOREIGN</span> <span class="token keyword">KEY</span> <span class="token punctuation">(</span>社团号<span class="token punctuation">)</span> <span class="token keyword">REFERENCES</span> 社团表<span class="token punctuation">(</span>社团号<span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-sql line-numbers-mode" data-ext="sql" data-title="sql"><pre v-pre class="language-sql"><code><span class="line"><span class="token comment">-- 插入社团表的数据</span></span>
<span class="line"><span class="token keyword">INSERT</span> <span class="token keyword">INTO</span> 社团表 <span class="token punctuation">(</span>社团号<span class="token punctuation">,</span> 名称<span class="token punctuation">,</span> 活动地点<span class="token punctuation">)</span> <span class="token keyword">VALUES</span> </span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C001'</span><span class="token punctuation">,</span> <span class="token string">'篮球社'</span><span class="token punctuation">,</span> <span class="token string">'体育馆'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C002'</span><span class="token punctuation">,</span> <span class="token string">'书法社'</span><span class="token punctuation">,</span> <span class="token string">'艺术楼202'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C003'</span><span class="token punctuation">,</span> <span class="token string">'编程社'</span><span class="token punctuation">,</span> <span class="token string">'计算机房305'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C004'</span><span class="token punctuation">,</span> <span class="token string">'音乐社'</span><span class="token punctuation">,</span> <span class="token string">'音乐教室101'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C005'</span><span class="token punctuation">,</span> <span class="token string">'摄影社'</span><span class="token punctuation">,</span> <span class="token string">'摄影工作室501'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">-- 插入学生表的数据</span></span>
<span class="line"><span class="token keyword">INSERT</span> <span class="token keyword">INTO</span> 学生表 <span class="token punctuation">(</span>学号<span class="token punctuation">,</span> 姓名<span class="token punctuation">,</span> 性别<span class="token punctuation">,</span> 出生日期<span class="token punctuation">)</span> <span class="token keyword">VALUES</span> </span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'S001'</span><span class="token punctuation">,</span> <span class="token string">'张伟'</span><span class="token punctuation">,</span> <span class="token string">'男'</span><span class="token punctuation">,</span> <span class="token string">'2001-05-12'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'S002'</span><span class="token punctuation">,</span> <span class="token string">'李娜'</span><span class="token punctuation">,</span> <span class="token string">'女'</span><span class="token punctuation">,</span> <span class="token string">'2002-08-09'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'S003'</span><span class="token punctuation">,</span> <span class="token string">'王强'</span><span class="token punctuation">,</span> <span class="token string">'男'</span><span class="token punctuation">,</span> <span class="token string">'2001-12-21'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'S004'</span><span class="token punctuation">,</span> <span class="token string">'赵敏'</span><span class="token punctuation">,</span> <span class="token string">'女'</span><span class="token punctuation">,</span> <span class="token string">'2003-03-15'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'S005'</span><span class="token punctuation">,</span> <span class="token string">'陈思'</span><span class="token punctuation">,</span> <span class="token string">'男'</span><span class="token punctuation">,</span> <span class="token string">'2002-11-30'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">-- 插入参加社团表的数据</span></span>
<span class="line"><span class="token keyword">INSERT</span> <span class="token keyword">INTO</span> 参加社团表 <span class="token punctuation">(</span>社团号<span class="token punctuation">,</span> 学号<span class="token punctuation">,</span> 加入时间<span class="token punctuation">)</span> <span class="token keyword">VALUES</span> </span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C001'</span><span class="token punctuation">,</span> <span class="token string">'S001'</span><span class="token punctuation">,</span> <span class="token string">'2023-09-01'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C001'</span><span class="token punctuation">,</span> <span class="token string">'S003'</span><span class="token punctuation">,</span> <span class="token string">'2023-09-05'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C002'</span><span class="token punctuation">,</span> <span class="token string">'S002'</span><span class="token punctuation">,</span> <span class="token string">'2023-09-03'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C003'</span><span class="token punctuation">,</span> <span class="token string">'S004'</span><span class="token punctuation">,</span> <span class="token string">'2023-09-07'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C004'</span><span class="token punctuation">,</span> <span class="token string">'S005'</span><span class="token punctuation">,</span> <span class="token string">'2023-09-10'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C005'</span><span class="token punctuation">,</span> <span class="token string">'S001'</span><span class="token punctuation">,</span> <span class="token string">'2023-09-12'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C003'</span><span class="token punctuation">,</span> <span class="token string">'S003'</span><span class="token punctuation">,</span> <span class="token string">'2023-09-15'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">(</span><span class="token string">'C002'</span><span class="token punctuation">,</span> <span class="token string">'S005'</span><span class="token punctuation">,</span> <span class="token string">'2023-09-17'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="p1" tabindex="-1"><a class="header-anchor" href="#p1"><span>p1</span></a></h3>
<div class="language-sql line-numbers-mode" data-ext="sql" data-title="sql"><pre v-pre class="language-sql"><code><span class="line"><span class="token keyword">CREATE</span> <span class="token operator">OR</span> <span class="token keyword">REPLACE</span> <span class="token keyword">PROCEDURE</span> p1<span class="token punctuation">(</span></span>
<span class="line">	community_id	<span class="token keyword">VARCHAR</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    student_id	<span class="token keyword">VARCHAR</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">AS</span> </span>
<span class="line"><span class="token keyword">DECLARE</span></span>
<span class="line"> 	SQL_STR <span class="token keyword">VARCHAR</span><span class="token punctuation">(</span><span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"> 	join_date <span class="token keyword">VARCHAR</span><span class="token punctuation">(</span><span class="token number">32</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">BEGIN</span></span>
<span class="line">	SQL_STR :<span class="token operator">=</span> <span class="token string">'SELECT 加入时间 FROM 参加社团表 WHERE 社团号 = $1 AND 学号 = $2;'</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">EXECUTE</span> IMMEDIATE SQL_STR <span class="token keyword">INTO</span> join_date <span class="token keyword">USING</span> community_id<span class="token punctuation">,</span>student_id<span class="token punctuation">;</span></span>
<span class="line">	RAISE NOTICE <span class="token string">'加入时间: %'</span><span class="token punctuation">,</span> join_date<span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">END</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token operator">/</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">CALL</span> p1<span class="token punctuation">(</span><span class="token string">'C001'</span><span class="token punctuation">,</span><span class="token string">'S003'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="p2" tabindex="-1"><a class="header-anchor" href="#p2"><span>p2</span></a></h3>
<div class="language-sql line-numbers-mode" data-ext="sql" data-title="sql"><pre v-pre class="language-sql"><code><span class="line"><span class="token keyword">CREATE</span> <span class="token operator">OR</span> <span class="token keyword">REPLACE</span> <span class="token keyword">PROCEDURE</span> p2<span class="token punctuation">(</span></span>
<span class="line">	community_id	<span class="token keyword">VARCHAR</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">AS</span> </span>
<span class="line"><span class="token keyword">DECLARE</span></span>
<span class="line"> 	SQL_STR <span class="token keyword">VARCHAR</span><span class="token punctuation">(</span><span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"> 	person_num <span class="token keyword">INTEGER</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">BEGIN</span></span>
<span class="line">	SQL_STR :<span class="token operator">=</span> <span class="token string">'SELECT count(*) FROM 参加社团表 WHERE 社团号 = $1'</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">EXECUTE</span> IMMEDIATE SQL_STR <span class="token keyword">INTO</span> person_num <span class="token keyword">USING</span> community_id<span class="token punctuation">;</span></span>
<span class="line">	RAISE NOTICE <span class="token string">'参加该社团人数: %'</span><span class="token punctuation">,</span> person_num<span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">END</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token operator">/</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">CALL</span> p2<span class="token punctuation">(</span><span class="token string">'C002'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="p3" tabindex="-1"><a class="header-anchor" href="#p3"><span>p3</span></a></h3>
<div class="language-sql line-numbers-mode" data-ext="sql" data-title="sql"><pre v-pre class="language-sql"><code><span class="line"><span class="token keyword">CREATE</span> <span class="token operator">OR</span> <span class="token keyword">REPLACE</span> <span class="token keyword">PROCEDURE</span> p3<span class="token punctuation">(</span></span>
<span class="line">    <span class="token operator">IN</span> community_id <span class="token keyword">CHAR</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">AS</span></span>
<span class="line"><span class="token keyword">DECLARE</span></span>
<span class="line">    male_count <span class="token keyword">INT</span> :<span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span></span>
<span class="line">    female_count <span class="token keyword">INT</span> :<span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span></span>
<span class="line">    gender <span class="token keyword">CHAR</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">CURSOR</span> cursor_student<span class="token punctuation">(</span>community_id <span class="token keyword">CHAR</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">is</span> </span>
<span class="line">		<span class="token keyword">SELECT</span> s<span class="token punctuation">.</span>性别</span>
<span class="line">        <span class="token keyword">FROM</span> 参加社团表 c</span>
<span class="line">        <span class="token keyword">JOIN</span> 学生表 s <span class="token keyword">ON</span> c<span class="token punctuation">.</span>学号 <span class="token operator">=</span> s<span class="token punctuation">.</span>学号</span>
<span class="line">        <span class="token keyword">WHERE</span> c<span class="token punctuation">.</span>社团号 <span class="token operator">=</span> community_id<span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">BEGIN</span></span>
<span class="line">    <span class="token comment">-- 打开游标</span></span>
<span class="line">    <span class="token keyword">OPEN</span> cursor_student<span class="token punctuation">(</span>community_id<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">-- 循环遍历游标结果集</span></span>
<span class="line">    <span class="token keyword">LOOP</span></span>
<span class="line">        <span class="token keyword">FETCH</span> cursor_student <span class="token keyword">INTO</span> gender<span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">EXIT</span> <span class="token keyword">WHEN</span> <span class="token operator">NOT</span> FOUND<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">-- 计算男生和女生人数</span></span>
<span class="line">        <span class="token keyword">IF</span> gender <span class="token operator">=</span> <span class="token string">'男'</span> <span class="token keyword">THEN</span></span>
<span class="line">            male_count :<span class="token operator">=</span> male_count <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">;</span></span>
<span class="line">        ELSIF gender <span class="token operator">=</span> <span class="token string">'女'</span> <span class="token keyword">THEN</span></span>
<span class="line">            female_count :<span class="token operator">=</span> female_count <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">END</span> <span class="token keyword">IF</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">END</span> <span class="token keyword">LOOP</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">-- 关闭游标</span></span>
<span class="line">    <span class="token keyword">CLOSE</span> cursor_student<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">-- 显示结果</span></span>
<span class="line">    RAISE NOTICE <span class="token string">'社团号: %, 男生人数: %, 女生人数: %'</span><span class="token punctuation">,</span> community_id<span class="token punctuation">,</span> male_count<span class="token punctuation">,</span> female_count<span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">END</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token operator">/</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">CALL</span> p3<span class="token punctuation">(</span><span class="token string">'C003'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="p4" tabindex="-1"><a class="header-anchor" href="#p4"><span>p4</span></a></h3>
<div class="language-sql line-numbers-mode" data-ext="sql" data-title="sql"><pre v-pre class="language-sql"><code><span class="line"><span class="token keyword">CREATE</span> <span class="token operator">OR</span> <span class="token keyword">REPLACE</span> <span class="token keyword">PROCEDURE</span> p4<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">AS</span> </span>
<span class="line"><span class="token keyword">DECLARE</span></span>
<span class="line">    <span class="token keyword">TYPE</span> CURSOR_TYPE <span class="token operator">IS</span> REF <span class="token keyword">CURSOR</span><span class="token punctuation">;</span>	<span class="token comment">--定义ref游标类型CURSOR_TYPE</span></span>
<span class="line">    C CURSOR_TYPE<span class="token punctuation">;</span></span>
<span class="line"> 	SQL_STR <span class="token keyword">VARCHAR</span><span class="token punctuation">(</span><span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"> 	community_id <span class="token keyword">VARCHAR</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"> 	community_name <span class="token keyword">VARCHAR</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">BEGIN</span></span>
<span class="line">	SQL_STR :<span class="token operator">=</span> <span class="token string">'SELECT 社团号,名称 FROM 社团表;'</span><span class="token punctuation">;</span></span>
<span class="line">    </span>
<span class="line">    <span class="token keyword">OPEN</span> C <span class="token keyword">FOR</span> SQL_STR<span class="token punctuation">;</span>		<span class="token comment">--绑定游标</span></span>
<span class="line">    <span class="token keyword">LOOP</span>									<span class="token comment">--开启循环</span></span>
<span class="line">        <span class="token keyword">FETCH</span> C <span class="token keyword">INTO</span> community_id<span class="token punctuation">,</span>community_name<span class="token punctuation">;</span>            <span class="token comment">--将结果赋值给变量join_date</span></span>
<span class="line">        <span class="token keyword">EXIT</span> <span class="token keyword">WHEN</span> C<span class="token operator">%</span>NOTFOUND<span class="token punctuation">;</span>			<span class="token comment">--如果查询结果为空则退出</span></span>
<span class="line">        RAISE NOTICE <span class="token string">'社团号: %,名称: %'</span><span class="token punctuation">,</span> community_id<span class="token punctuation">,</span>community_name<span class="token punctuation">;</span>		<span class="token comment">--将结果输入到屏幕上</span></span>
<span class="line">    <span class="token keyword">END</span> <span class="token keyword">LOOP</span><span class="token punctuation">;</span>								<span class="token comment">--结束循环</span></span>
<span class="line">    <span class="token keyword">CLOSE</span> C<span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">END</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token operator">/</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">CALL</span> p4<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


