<template><div><h1 id="go组件学习——gorm四步带你搞定db增删改查" tabindex="-1"><a class="header-anchor" href="#go组件学习——gorm四步带你搞定db增删改查"><span>Go组件学习——gorm四步带你搞定DB增删改查</span></a></h1>
<h3 id="_1、简介" tabindex="-1"><a class="header-anchor" href="#_1、简介"><span>1、简介</span></a></h3>
<p><strong>ORM</strong></p>
<p>Object-Relationl Mapping， 它的作用是映射数据库和对象之间的关系，方便我们在实现数据库操作的时候不用去写复杂的sql语句，把对数据库的操作上升到对于对象的操作。</p>
<p><strong>gorm</strong></p>
<p>gorm就是基于Go语言实现的ORM库。</p>
<p>类似于Java生态里大家听到过的Mybatis、Hibernate、SpringData等。</p>
<p><strong>Github</strong></p>
<p><a href="https://links.jianshu.com/go?to=https%3A%2F%2Fgithub.com%2Fjinzhu%2Fgorm" target="_blank" rel="noopener noreferrer">https://github.com/jinzhu/gorm</a></p>
<p><strong>官方文档</strong></p>
<p><a href="https://links.jianshu.com/go?to=https%3A%2F%2Fgorm.io%2F" target="_blank" rel="noopener noreferrer">https://gorm.io/</a></p>
<h3 id="_2、如何使用gorm" tabindex="-1"><a class="header-anchor" href="#_2、如何使用gorm"><span>2、如何使用Gorm</span></a></h3>
<p>只要四步就能上手gorm，可以尽情的沉浸在毫无技术含量的CRUD世界。</p>
<h4 id="_2-1-下载gorm库" tabindex="-1"><a class="header-anchor" href="#_2-1-下载gorm库"><span>2.1 下载gorm库</span></a></h4>
<div class="language-bash line-numbers-mode" data-ext="sh" data-title="sh"><pre v-pre class="language-bash"><code><span class="line">go get <span class="token parameter variable">-u</span> gorm.io/gorm</span>
<span class="line">go get <span class="token parameter variable">-u</span> gorm.io/driver/mysql</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_2-2-创建db连接" tabindex="-1"><a class="header-anchor" href="#_2-2-创建db连接"><span>2.2 创建DB连接</span></a></h4>
<p>建立数据库连接</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">package</span> main</span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">(</span></span>
<span class="line">  <span class="token string">"github.com/jinzhu/gorm"</span></span>
<span class="line">    <span class="token boolean">_</span> <span class="token string">"github.com/jinzhu/gorm/dialects/mysql"</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">func</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">var</span> err <span class="token builtin">error</span></span>
<span class="line">    db<span class="token punctuation">,</span> connErr <span class="token operator">:=</span> gorm<span class="token punctuation">.</span><span class="token function">Open</span><span class="token punctuation">(</span><span class="token string">"mysql"</span><span class="token punctuation">,</span> <span class="token string">"root:rootroot@/dqm?charset=utf8&amp;parseTime=True&amp;loc=Local"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">if</span> connErr <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token function">panic</span><span class="token punctuation">(</span><span class="token string">"failed to connect database"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">defer</span> db<span class="token punctuation">.</span><span class="token function">Close</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">  db<span class="token punctuation">.</span><span class="token function">SingularTable</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>gorm支持很多数据源包括PostgreSQL、MySQL等。</p>
<p>这里连接的是MySQL，所以需要引用&quot;github.com/jinzhu/gorm/dialects/mysql&quot;驱动。</p>
<p>通过上面声明，已经获取数据库的连接。</p>
<p>db.SingularTable(true)这句的作用后面会提到。</p>
<h4 id="_2-3-创建映射表结构的struct" tabindex="-1"><a class="header-anchor" href="#_2-3-创建映射表结构的struct"><span>2.3 创建映射表结构的struct</span></a></h4>
<p>定义数据库表结构对应的struct</p>
<p>比如这里我们要操作的是表test表，表结构如下</p>
<div class="language-sql line-numbers-mode" data-ext="sql" data-title="sql"><pre v-pre class="language-sql"><code><span class="line"><span class="token keyword">CREATE</span> <span class="token keyword">TABLE</span> <span class="token identifier"><span class="token punctuation">`</span>test<span class="token punctuation">`</span></span> <span class="token punctuation">(</span></span>
<span class="line">  <span class="token identifier"><span class="token punctuation">`</span>id<span class="token punctuation">`</span></span> <span class="token keyword">bigint</span><span class="token punctuation">(</span><span class="token number">20</span><span class="token punctuation">)</span> <span class="token operator">NOT</span> <span class="token boolean">NULL</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token identifier"><span class="token punctuation">`</span>name<span class="token punctuation">`</span></span> <span class="token keyword">varchar</span><span class="token punctuation">(</span><span class="token number">5</span><span class="token punctuation">)</span> <span class="token keyword">DEFAULT</span> <span class="token boolean">NULL</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token identifier"><span class="token punctuation">`</span>age<span class="token punctuation">`</span></span> <span class="token keyword">int</span><span class="token punctuation">(</span><span class="token number">11</span><span class="token punctuation">)</span> <span class="token keyword">DEFAULT</span> <span class="token boolean">NULL</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token keyword">PRIMARY</span> <span class="token keyword">KEY</span> <span class="token punctuation">(</span><span class="token identifier"><span class="token punctuation">`</span>id<span class="token punctuation">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">)</span> <span class="token keyword">ENGINE</span><span class="token operator">=</span><span class="token keyword">InnoDB</span> <span class="token keyword">DEFAULT</span> <span class="token keyword">CHARSET</span><span class="token operator">=</span>utf8mb4 <span class="token keyword">COLLATE</span><span class="token operator">=</span>utf8mb4_0900_ai_ci</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>于是我们对应可以定义struct结构如下</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">type</span> Test <span class="token keyword">struct</span> <span class="token punctuation">{</span></span>
<span class="line">    ID   <span class="token builtin">int64</span>  <span class="token string">`gorm:"type:bigint(20);column:id;primary_key"`</span></span>
<span class="line">    Name <span class="token builtin">string</span> <span class="token string">`gorm:"type:varchar(5);column:name"`</span></span>
<span class="line">    Age  <span class="token builtin">int</span>    <span class="token string">`gorm:"type:int(11);column:age"`</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>每个字段后面的gorm是结构标记，可以用于声明对应数据库字段的属性。</p>
<p>比如ID后面的约束为该字段为bigint(20)类型，对应列表为id，且该字段为主键。</p>
<p>除此以外，还有更加丰富的标签定义参见官方文档：<a href="https://links.jianshu.com/go?to=http%3A%2F%2Fgorm.io%2Fzh_CN%2Fdocs%2Fmodels.html" target="_blank" rel="noopener noreferrer">http://gorm.io/zh_CN/docs/models.html</a></p>
<h4 id="_2-4-crud" tabindex="-1"><a class="header-anchor" href="#_2-4-crud"><span>2.4 CRUD</span></a></h4>
<p>有了前面三步的铺垫，下面就可以执行真正写数据库操作了。</p>
<p>比如&quot;增&quot;</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line">test <span class="token operator">:=</span> <span class="token operator">&amp;</span>Test<span class="token punctuation">{</span></span>
<span class="line">        ID<span class="token punctuation">:</span><span class="token number">3</span><span class="token punctuation">,</span></span>
<span class="line">        Name<span class="token punctuation">:</span><span class="token string">"jackie"</span><span class="token punctuation">,</span></span>
<span class="line">        Age<span class="token punctuation">:</span><span class="token number">18</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    db<span class="token punctuation">.</span><span class="token function">Create</span><span class="token punctuation">(</span>test<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>比如&quot;删&quot;</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line">test <span class="token operator">:=</span> <span class="token operator">&amp;</span>Test<span class="token punctuation">{</span></span>
<span class="line">        ID<span class="token punctuation">:</span><span class="token number">3</span><span class="token punctuation">,</span></span>
<span class="line">        Name<span class="token punctuation">:</span><span class="token string">"jackie"</span><span class="token punctuation">,</span></span>
<span class="line">        Age<span class="token punctuation">:</span><span class="token number">18</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Delete</span><span class="token punctuation">(</span>test<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>比如&quot;改&quot;</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line">test <span class="token operator">:=</span> <span class="token operator">&amp;</span>Test<span class="token punctuation">{</span></span>
<span class="line">        ID<span class="token punctuation">:</span>   <span class="token number">3</span><span class="token punctuation">,</span></span>
<span class="line">        Name<span class="token punctuation">:</span> <span class="token string">"hello"</span><span class="token punctuation">,</span></span>
<span class="line">        Age<span class="token punctuation">:</span>  <span class="token number">18</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Model</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>test<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Update</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">,</span> <span class="token string">"world"</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>比如&quot;查&quot;</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> testResult Test</span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"name = ?"</span><span class="token punctuation">,</span> <span class="token string">"hello"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">First</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>testResult<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"result: "</span><span class="token punctuation">,</span> testResult<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如果只是想做个纯粹的CRUDer，掌握上面四步就算是会用gorm了。</p>
<p>如果还想来点花式的，更深入的，继续往下看~~~</p>
<h3 id="_3、表名和结构体如何映射" tabindex="-1"><a class="header-anchor" href="#_3、表名和结构体如何映射"><span>3、表名和结构体如何映射</span></a></h3>
<p>从上面四步，我们只看到在创建DB链接的时候，提供的信息仅仅到数据库，那么gorm是如何做到将表结构和你定义的struct映射起来的呢？</p>
<p>有三种方式可以实现，如果以下三种方式都没有实现，如果你是创建表，则gorm默认会在你定义的struct名后面加上”s“，比如上面就会创建tests表。</p>
<h4 id="_3-1-db-singulartable-true" tabindex="-1"><a class="header-anchor" href="#_3-1-db-singulartable-true"><span>3.1 db.SingularTable(true)</span></a></h4>
<p>通过db.SingularTable(true)，gorm会在创建表的时候去掉”s“的后缀</p>
<h4 id="_3-2-实现tablename方法" tabindex="-1"><a class="header-anchor" href="#_3-2-实现tablename方法"><span>3.2 实现TableName方法</span></a></h4>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>Test<span class="token punctuation">)</span> <span class="token function">TableName</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token builtin">string</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token string">"test"</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>TableName方法定义在scope.go的tabler接口中</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">type</span> tabler <span class="token keyword">interface</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token function">TableName</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token builtin">string</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_3-3-通过table-api声明" tabindex="-1"><a class="header-anchor" href="#_3-3-通过table-api声明"><span>3.3 通过Table API声明</span></a></h4>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line">db<span class="token punctuation">.</span><span class="token function">Table</span><span class="token punctuation">(</span><span class="token string">"test"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"name = ?"</span><span class="token punctuation">,</span> <span class="token string">"hello"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">First</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>testResult<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>在CRUD前，指明需要操作的表名也是OK的。</p>
<h3 id="_4、其他花式操作" tabindex="-1"><a class="header-anchor" href="#_4、其他花式操作"><span>4、其他花式操作</span></a></h3>
<p>下面花式API操作使用表dqm_user_role，对应struct如下</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">type</span> DqmUserRole <span class="token keyword">struct</span> <span class="token punctuation">{</span></span>
<span class="line">    ID        <span class="token builtin">int64</span>     <span class="token string">`gorm:"column:id;primary_key" json:"id"`</span></span>
<span class="line">    UserId    <span class="token builtin">string</span>    <span class="token string">`gorm:"column:user_id" json:"user_id"`</span></span>
<span class="line">    RoleId    <span class="token builtin">string</span>    <span class="token string">`gorm:"column:role_id" json:"role_id"`</span></span>
<span class="line">    CreatedAt time<span class="token punctuation">.</span>Time <span class="token string">`gorm:"column:created_at" json:"created_at"`</span></span>
<span class="line">    UpdatedAt time<span class="token punctuation">.</span>Time <span class="token string">`gorm:"column:updated_at" json:"updated_at"`</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>以下API均亲测可用</p>
<p><strong>First</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRole DqmUserRole</span>
<span class="line"><span class="token comment">// 按照主键顺序的第一条记录</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">First</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"roleId: "</span><span class="token punctuation">,</span> dqmUserRole<span class="token punctuation">.</span>RoleId<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>Last</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRole1 DqmUserRole</span>
<span class="line"><span class="token comment">// 按照主键顺序的最后一条记录</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Last</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole1<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"roleId: "</span><span class="token punctuation">,</span> dqmUserRole1<span class="token punctuation">.</span>RoleId<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>Find</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRoels <span class="token punctuation">[</span><span class="token punctuation">]</span>DqmUserRole</span>
<span class="line"><span class="token comment">// 所有记录</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRoels<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"dqmUserRoles: "</span><span class="token punctuation">,</span> dqmUserRoels<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>Where</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRole3 DqmUserRole</span>
<span class="line"><span class="token comment">// 根据条件查询得到满足条件的第一条记录</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"role_id = ?"</span><span class="token punctuation">,</span> <span class="token string">"2"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">First</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole3<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"where roleId: "</span><span class="token punctuation">,</span> dqmUserRole3<span class="token punctuation">.</span>RoleId<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">var</span> dqmUserRoles4 <span class="token punctuation">[</span><span class="token punctuation">]</span>DqmUserRole</span>
<span class="line"><span class="token comment">// 根据条件查询得到满足条件的所有记录</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"user_id = ?"</span><span class="token punctuation">,</span> <span class="token string">"1"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRoles4<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"where dqmUserRoles: "</span><span class="token punctuation">,</span> dqmUserRoles4<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">var</span> dqmUserRole5 <span class="token punctuation">[</span><span class="token punctuation">]</span>DqmUserRole</span>
<span class="line"><span class="token comment">// like模糊查询</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"role_id like ?"</span><span class="token punctuation">,</span> <span class="token string">"%2"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole5<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"where dqmUserRoles: "</span><span class="token punctuation">,</span> dqmUserRole5<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">var</span> dqmUserRole6 <span class="token punctuation">[</span><span class="token punctuation">]</span>DqmUserRole</span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"updated_at > ?"</span><span class="token punctuation">,</span> <span class="token string">"2019-02-08 18:08:27"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole6<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"where dqmUserRoles: "</span><span class="token punctuation">,</span> dqmUserRole6<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">var</span> dqmUserRole7 DqmUserRole</span>
<span class="line"><span class="token comment">// struct结构查询条件</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>DqmUserRole<span class="token punctuation">{</span>RoleId<span class="token punctuation">:</span> <span class="token string">"1,2"</span><span class="token punctuation">,</span> UserId<span class="token punctuation">:</span> <span class="token string">"1"</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">First</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole7<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"where dqmUserRole: "</span><span class="token punctuation">,</span> dqmUserRole7<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">var</span> dqmUserRole8 DqmUserRole</span>
<span class="line"><span class="token comment">// map结构查询条件</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">{</span><span class="token string">"role_id"</span><span class="token punctuation">:</span> <span class="token string">"1,2"</span><span class="token punctuation">,</span> <span class="token string">"user_id"</span><span class="token punctuation">:</span> <span class="token string">"1"</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole8<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"where dqmUserRole: "</span><span class="token punctuation">,</span> dqmUserRole8<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>Not</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRole9 DqmUserRole</span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Not</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">int64</span><span class="token punctuation">{</span><span class="token number">1</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">First</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole9<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"not dqmUserRole: "</span><span class="token punctuation">,</span> dqmUserRole9<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>Or</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRole10 <span class="token punctuation">[</span><span class="token punctuation">]</span>DqmUserRole</span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>DqmUserRole<span class="token punctuation">{</span>RoleId<span class="token punctuation">:</span> <span class="token string">"1,2"</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Or</span><span class="token punctuation">(</span><span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">{</span><span class="token string">"user_id"</span><span class="token punctuation">:</span> <span class="token string">"2"</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole10<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"or dqmUserRoles: "</span><span class="token punctuation">,</span> dqmUserRole10<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>FirstOrInit和Attrs</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRole11 DqmUserRole</span>
<span class="line"><span class="token comment">// 查不到该条记录，则使用attrs值替换</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"user_id = ?"</span><span class="token punctuation">,</span> <span class="token string">"0"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Attrs</span><span class="token punctuation">(</span><span class="token string">"role_id"</span><span class="token punctuation">,</span> <span class="token string">"12"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">FirstOrInit</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole11<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"after FirstOrInit: "</span><span class="token punctuation">,</span> dqmUserRole11<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">var</span> dqmUserRole12 DqmUserRole</span>
<span class="line"><span class="token comment">// 查到记录，则使用数据库中的值</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"user_id = ?"</span><span class="token punctuation">,</span> <span class="token string">"1"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Attrs</span><span class="token punctuation">(</span><span class="token string">"role_id"</span><span class="token punctuation">,</span> <span class="token string">"2"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">FirstOrInit</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole12<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"after FirstOrInit: "</span><span class="token punctuation">,</span> dqmUserRole12<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>FirstOrInit和Assign</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRole13 DqmUserRole</span>
<span class="line"><span class="token comment">// 不管是否找到对应记录，使用Assign值替代查询到的值</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"role_id = ?"</span><span class="token punctuation">,</span> <span class="token string">"1,2"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Assign</span><span class="token punctuation">(</span>DqmUserRole<span class="token punctuation">{</span>UserId<span class="token punctuation">:</span> <span class="token string">"15"</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">FirstOrInit</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole13<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"assign dqmUserRole: "</span><span class="token punctuation">,</span> dqmUserRole13<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>FirstOrCreate</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRole14 DqmUserRole</span>
<span class="line"><span class="token comment">// 如果记录存在则返回结果，如果不存在则创建</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>DqmUserRole<span class="token punctuation">{</span>UserId<span class="token punctuation">:</span> <span class="token string">"3"</span><span class="token punctuation">,</span> RoleId<span class="token punctuation">:</span> <span class="token string">"3"</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">FirstOrCreate</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole14<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"firstOrCreate dqmUserRole: "</span><span class="token punctuation">,</span> dqmUserRole14<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>Order</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRole16 <span class="token punctuation">[</span><span class="token punctuation">]</span>DqmUserRole</span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Order</span><span class="token punctuation">(</span><span class="token string">"user_id desc"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole16<span class="token punctuation">)</span> <span class="token comment">// 注意这里的order要在find前面，否则不生效</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"order dqmUserRoles: "</span><span class="token punctuation">,</span> dqmUserRole16<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>Limit和Offset</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRole18 <span class="token punctuation">[</span><span class="token punctuation">]</span>DqmUserRole</span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Limit</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Offset</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole18<span class="token punctuation">)</span> <span class="token comment">// 如果只有offset没有limit则不会生效</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"offset dqmUserRoles: "</span><span class="token punctuation">,</span> dqmUserRole18<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>Scan</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">type</span> Result <span class="token keyword">struct</span> <span class="token punctuation">{</span></span>
<span class="line">        Id <span class="token builtin">int64</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">var</span> results <span class="token punctuation">[</span><span class="token punctuation">]</span>Result</span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Select</span><span class="token punctuation">(</span><span class="token string">"id"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"user_id in (?)"</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">{</span><span class="token string">"1"</span><span class="token punctuation">,</span> <span class="token string">"2"</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole20<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Scan</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>results<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"ids: "</span><span class="token punctuation">,</span> results<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>支持执行原生sql</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRole24 <span class="token punctuation">[</span><span class="token punctuation">]</span>DqmUserRole</span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Exec</span><span class="token punctuation">(</span><span class="token string">"select * from dqm_user_role"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole24<span class="token punctuation">)</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"sql dqmUserRole: "</span><span class="token punctuation">,</span> dqmUserRole24<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>事务</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line">tx <span class="token operator">:=</span> db<span class="token punctuation">.</span><span class="token function">Begin</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">defer</span> <span class="token keyword">func</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">if</span> r <span class="token operator">:=</span> <span class="token function">recover</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> r <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">    tx<span class="token punctuation">.</span><span class="token function">Rollback</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">if</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">    tx<span class="token punctuation">.</span><span class="token function">Rollback</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">    tx<span class="token punctuation">.</span><span class="token function">Commit</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">if</span> err <span class="token operator">=</span> tx<span class="token punctuation">.</span><span class="token function">Create</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>DqmUserRole<span class="token punctuation">{</span>UserId<span class="token punctuation">:</span> <span class="token string">"8"</span><span class="token punctuation">,</span> RoleId<span class="token punctuation">:</span> <span class="token string">"8"</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span>Error<span class="token punctuation">;</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token comment">//tx.Rollback()</span></span>
<span class="line">    <span class="token comment">//return</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">if</span> err <span class="token operator">=</span> tx<span class="token punctuation">.</span><span class="token function">Create</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>DqmUserRole<span class="token punctuation">{</span>UserId<span class="token punctuation">:</span> <span class="token string">"9"</span><span class="token punctuation">,</span> RoleId<span class="token punctuation">:</span> <span class="token string">"9"</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span>Error<span class="token punctuation">;</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//tx.Rollback()</span></span>
<span class="line">    <span class="token comment">//return</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>错误处理</strong></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">var</span> dqmUserRole25 DqmUserRole</span>
<span class="line">err <span class="token operator">=</span> db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"role_id = ?"</span><span class="token punctuation">,</span> <span class="token number">54321</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">First</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>dqmUserRole25<span class="token punctuation">)</span><span class="token punctuation">.</span>Error</span>
<span class="line"><span class="token keyword">if</span> err <span class="token operator">==</span> gorm<span class="token punctuation">.</span>ErrRecordNotFound <span class="token punctuation">{</span></span>
<span class="line">  fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"ErrRecordNotFound, record not found"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">  fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"err: "</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line">fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token string">"err dqmUserRole: "</span><span class="token punctuation">,</span> dqmUserRole25<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_5、总结" tabindex="-1"><a class="header-anchor" href="#_5、总结"><span>5、总结</span></a></h3>
<p>gorm作为一款orm库，几乎满足了一个CRUDer的一切想象。实现灵活，花样繁多。</p>
<p>有了gorm，就不需要再在代码中维护sql语句了。</p>
<p>后面有时间会再看看gorm的实现，作为国人开源的第一个orm库，目前star已经超过15k，值得深入学习下。</p>
</div></template>


