<template><div><h1 id="gorm的关联" tabindex="-1"><a class="header-anchor" href="#gorm的关联"><span>gorm的关联</span></a></h1>
<h2 id="预加载" tabindex="-1"><a class="header-anchor" href="#预加载"><span>预加载</span></a></h2>
<p>GORM 允许在 <code v-pre>Preload</code> 的其它 SQL 中直接加载关系，例如：</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">type</span> User <span class="token keyword">struct</span> <span class="token punctuation">{</span></span>
<span class="line">  gorm<span class="token punctuation">.</span>Model</span>
<span class="line">  Username <span class="token builtin">string</span></span>
<span class="line">  Orders   <span class="token punctuation">[</span><span class="token punctuation">]</span>Order</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">type</span> Order <span class="token keyword">struct</span> <span class="token punctuation">{</span></span>
<span class="line">  gorm<span class="token punctuation">.</span>Model</span>
<span class="line">  UserID <span class="token builtin">uint</span></span>
<span class="line">  Price  <span class="token builtin">float64</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 查找 user 时预加载相关 Order</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span><span class="token string">"Orders"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>users<span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// SELECT * FROM users;</span></span>
<span class="line"><span class="token comment">// SELECT * FROM orders WHERE user_id IN (1,2,3,4);</span></span>
<span class="line"></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span><span class="token string">"Orders"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span><span class="token string">"Profile"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span><span class="token string">"Role"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>users<span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// SELECT * FROM users;</span></span>
<span class="line"><span class="token comment">// SELECT * FROM orders WHERE user_id IN (1,2,3,4); // has many</span></span>
<span class="line"><span class="token comment">// SELECT * FROM profiles WHERE user_id IN (1,2,3,4); // has one</span></span>
<span class="line"><span class="token comment">// SELECT * FROM roles WHERE id IN (4,5,6); // belongs to</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="joins-预加载" tabindex="-1"><a class="header-anchor" href="#joins-预加载"><span>Joins 预加载</span></a></h2>
<p><code v-pre>Preload</code> 在一个单独查询中加载关联数据。而 <code v-pre>Join Preload</code> 会使用 inner join 加载关联数据，例如：</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line">db<span class="token punctuation">.</span><span class="token function">Joins</span><span class="token punctuation">(</span><span class="token string">"Company"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Joins</span><span class="token punctuation">(</span><span class="token string">"Manager"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Joins</span><span class="token punctuation">(</span><span class="token string">"Account"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">First</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>user<span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Joins</span><span class="token punctuation">(</span><span class="token string">"Company"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Joins</span><span class="token punctuation">(</span><span class="token string">"Manager"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Joins</span><span class="token punctuation">(</span><span class="token string">"Account"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">First</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>user<span class="token punctuation">,</span> <span class="token string">"users.name = ?"</span><span class="token punctuation">,</span> <span class="token string">"jinzhu"</span><span class="token punctuation">)</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Joins</span><span class="token punctuation">(</span><span class="token string">"Company"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Joins</span><span class="token punctuation">(</span><span class="token string">"Manager"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Joins</span><span class="token punctuation">(</span><span class="token string">"Account"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>users<span class="token punctuation">,</span> <span class="token string">"users.id IN ?"</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">int</span><span class="token punctuation">{</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">2</span><span class="token punctuation">,</span><span class="token number">3</span><span class="token punctuation">,</span><span class="token number">4</span><span class="token punctuation">,</span><span class="token number">5</span><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p><strong>注意</strong> <code v-pre>Join Preload</code> 适用于一对一的关系，例如： <code v-pre>has one</code>, <code v-pre>belongs to</code></p>
</blockquote>
<h2 id="预加载全部" tabindex="-1"><a class="header-anchor" href="#预加载全部"><span>预加载全部</span></a></h2>
<p>与创建、更新时使用 <code v-pre>Select</code> 类似，<code v-pre>clause.Associations</code> 也可以和 <code v-pre>Preload</code> 一起使用，它可以用来 <code v-pre>预加载</code> 全部关联，例如：</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token keyword">type</span> User <span class="token keyword">struct</span> <span class="token punctuation">{</span></span>
<span class="line">  gorm<span class="token punctuation">.</span>Model</span>
<span class="line">  Name       <span class="token builtin">string</span></span>
<span class="line">  CompanyID  <span class="token builtin">uint</span></span>
<span class="line">  Company    Company</span>
<span class="line">  Role       Role</span>
<span class="line">  Orders     <span class="token punctuation">[</span><span class="token punctuation">]</span>Order</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span>clause<span class="token punctuation">.</span>Associations<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>users<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>clause.Associations</code> 不会预加载嵌套的关联，但你可以使用<a href="https://gorm.io/zh_CN/docs/preload.html#nested_preloading" target="_blank" rel="noopener noreferrer">嵌套预加载</a> 例如：</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line">db<span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span><span class="token string">"Orders.OrderItems.Product"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span>clause<span class="token punctuation">.</span>Associations<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>users<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="带条件的预加载" tabindex="-1"><a class="header-anchor" href="#带条件的预加载"><span>带条件的预加载</span></a></h2>
<p>GORM 允许带条件的 Preload 关联，类似于<a href="https://gorm.io/zh_CN/docs/query.html#inline_conditions" target="_blank" rel="noopener noreferrer">内联条件</a></p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line"><span class="token comment">// 带条件的预加载 Order</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span><span class="token string">"Orders"</span><span class="token punctuation">,</span> <span class="token string">"state NOT IN (?)"</span><span class="token punctuation">,</span> <span class="token string">"cancelled"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>users<span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// SELECT * FROM users;</span></span>
<span class="line"><span class="token comment">// SELECT * FROM orders WHERE user_id IN (1,2,3,4) AND state NOT IN ('cancelled');</span></span>
<span class="line"></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"state = ?"</span><span class="token punctuation">,</span> <span class="token string">"active"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span><span class="token string">"Orders"</span><span class="token punctuation">,</span> <span class="token string">"state NOT IN (?)"</span><span class="token punctuation">,</span> <span class="token string">"cancelled"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>users<span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// SELECT * FROM users WHERE state = 'active';</span></span>
<span class="line"><span class="token comment">// SELECT * FROM orders WHERE user_id IN (1,2) AND state NOT IN ('cancelled');</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="自定义预加载-sql" tabindex="-1"><a class="header-anchor" href="#自定义预加载-sql"><span>自定义预加载 SQL</span></a></h2>
<p>您可以通过 <code v-pre>func(db *gorm.DB) *gorm.DB</code> 实现自定义预加载 SQL，例如：</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line">db<span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span><span class="token string">"Orders"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span>db <span class="token operator">*</span>gorm<span class="token punctuation">.</span>DB<span class="token punctuation">)</span> <span class="token operator">*</span>gorm<span class="token punctuation">.</span>DB <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">return</span> db<span class="token punctuation">.</span><span class="token function">Order</span><span class="token punctuation">(</span><span class="token string">"orders.amount DESC"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>users<span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// SELECT * FROM users;</span></span>
<span class="line"><span class="token comment">// SELECT * FROM orders WHERE user_id IN (1,2,3,4) order by orders.amount DESC;</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="嵌套预加载" tabindex="-1"><a class="header-anchor" href="#嵌套预加载"><span>嵌套预加载</span></a></h2>
<p>GORM 支持嵌套预加载，例如：</p>
<div class="language-go line-numbers-mode" data-ext="go" data-title="go"><pre v-pre class="language-go"><code><span class="line">db<span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span><span class="token string">"Orders.OrderItems.Product"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span><span class="token string">"CreditCard"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>users<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 自定义预加载 `Orders` 的条件</span></span>
<span class="line"><span class="token comment">// 这样，GORM 就不会加载不匹配的 order 记录</span></span>
<span class="line">db<span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span><span class="token string">"Orders"</span><span class="token punctuation">,</span> <span class="token string">"state = ?"</span><span class="token punctuation">,</span> <span class="token string">"paid"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Preload</span><span class="token punctuation">(</span><span class="token string">"Orders.OrderItems"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Find</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>users<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


